# Generated by Django 4.2 on 2025-11-19 09:28

import apps.file_manager.models
import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=500, upload_to=apps.file_manager.models.upload_file_with_dir)),
                ('action_status', models.CharField(choices=[('IS_ACTIVE', 'Is Active'), ('DELETED', 'Deleted')], default='IS_ACTIVE', max_length=50)),
                ('file_status', models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Not Approved', 'Not Approved')], max_length=50, null=True)),
                ('file_type', models.CharField(blank=True, choices=[('Contract', 'Contract'), ('Invoice', 'Invoice'), ('Statement', 'Statement')], max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
                ('action_status', models.CharField(choices=[('IS_ACTIVE', 'Is Active'), ('DELETED', 'Deleted')], default='IS_ACTIVE', max_length=50)),
                ('folder_status', models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Not Approved', 'Not Approved')], max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
