# Generated by Django 4.2 on 2025-11-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0002_alter_datefilter_parent_alter_userfilter_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datefilter',
            name='parent',
            field=models.CharField(choices=[('HR_STAFF_LIST_TERMINATIONS', 'HRStaffListTerminations'), ('HR_STAFF_LIST', 'HRStaffList'), ('FAVORITE', 'Favorite'), ('UNIQUE', 'Unique'), ('FINDING', 'Finding'), ('TAB', 'Tab'), ('COPY_DT', 'Copy DT'), ('FINDING_VIEW', 'Finding View'), ('IMAGE_LOADER', 'Image Loader'), ('IMAGES', 'Images'), ('FINDING_ATTACHMENT', 'Finding Attachment')], max_length=255),
        ),
        migrations.AlterField(
            model_name='userfilter',
            name='parent',
            field=models.CharField(choices=[('HR_STAFF_LIST_TERMINATIONS', 'HRStaffListTerminations'), ('HR_STAFF_LIST', 'HRStaffList'), ('FAVORITE', 'Favorite'), ('UNIQUE', 'Unique'), ('FINDING', 'Finding'), ('TAB', 'Tab'), ('COPY_DT', 'Copy DT'), ('FINDING_VIEW', 'Finding View'), ('IMAGE_LOADER', 'Image Loader'), ('IMAGES', 'Images'), ('FINDING_ATTACHMENT', 'Finding Attachment')], max_length=255),
        ),
    ]
