# Generated by Django 4.2 on 2025-11-19 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('field_name', models.CharField(max_length=255)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('change_date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='secure_file')),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DELETED', 'Deleted')], default='ACTIVE', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SavedFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField()),
                ('parent', models.CharField(choices=[('FAVORITE', 'Favorite'), ('UNIQUE', 'Unique'), ('FINDING', 'Finding'), ('TAB', 'Tab'), ('COPY_DT', 'Copy DT'), ('FINDING_VIEW', 'Finding View'), ('IMAGE_LOADER', 'Image Loader'), ('IMAGES', 'Images'), ('FINDING_ATTACHMENT', 'Finding Attachment')], max_length=255)),
                ('field_name', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('TEXT', 'Text or Character'), ('DATE', 'Date'), ('INT', 'Integer'), ('FLOAT', 'Float')], max_length=20)),
                ('value_start', models.CharField(blank=True, max_length=100, null=True)),
                ('value_end', models.CharField(blank=True, max_length=100, null=True)),
                ('is_not', models.BooleanField(default=False)),
                ('is_null', models.BooleanField(default=False)),
                ('is_not_null', models.BooleanField(default=False)),
                ('is_unique', models.BooleanField(default=False)),
                ('is_count', models.BooleanField(default=False)),
                ('s_model_choice', models.CharField(blank=True, choices=[('FAVORITE', 'Favorite'), ('UNIQUE', 'Unique'), ('FINDING', 'Finding'), ('TAB', 'Tab'), ('COPY_DT', 'Copy DT'), ('FINDING_VIEW', 'Finding View'), ('IMAGE_LOADER', 'Image Loader'), ('IMAGES', 'Images'), ('FINDING_ATTACHMENT', 'Finding Attachment')], max_length=255, null=True, verbose_name='Source Model Choice')),
                ('is_hidden', models.BooleanField(default=False)),
                ('favorite_id', models.TextField(blank=True, null=True)),
                ('finding_id', models.TextField(blank=True, null=True)),
                ('img_loader_id', models.TextField(blank=True, null=True)),
                ('unique_id', models.TextField(blank=True, null=True)),
                ('tab_id', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sidebar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('segment', models.CharField(blank=True, max_length=255, null=True)),
                ('url_name', models.CharField(blank=True, max_length=255, null=True)),
                ('dynamic_url', models.CharField(blank=True, max_length=255, null=True)),
                ('icon', models.TextField(blank=True, help_text='SVG image only', null=True)),
                ('info', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.sidebar')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
