# Generated by Django 4.2 on 2025-11-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_savedfilter_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedfilter',
            name='parent',
            field=models.CharField(choices=[('HR_STAFF_LIST_TERMINATIONS', 'HRStaffListTerminations'), ('HR_STAFF_LIST', 'HRStaffList'), ('FAVORITE', 'Favorite'), ('UNIQUE', 'Unique'), ('FINDING', 'Finding'), ('TAB', 'Tab'), ('COPY_DT', 'Copy DT'), ('FINDING_VIEW', 'Finding View'), ('IMAGE_LOADER', 'Image Loader'), ('IMAGES', 'Images'), ('FINDING_ATTACHMENT', 'Finding Attachment')], max_length=255),
        ),
        migrations.AlterField(
            model_name='savedfilter',
            name='s_model_choice',
            field=models.CharField(blank=True, choices=[('HR_STAFF_LIST_TERMINATIONS', 'HRStaffListTerminations'), ('HR_STAFF_LIST', 'HRStaffList'), ('FAVORITE', 'Favorite'), ('UNIQUE', 'Unique'), ('FINDING', 'Finding'), ('TAB', 'Tab'), ('COPY_DT', 'Copy DT'), ('FINDING_VIEW', 'Finding View'), ('IMAGE_LOADER', 'Image Loader'), ('IMAGES', 'Images'), ('FINDING_ATTACHMENT', 'Finding Attachment')], max_length=255, null=True, verbose_name='Source Model Choice'),
        ),
    ]
