# Generated by Django 4.2 on 2025-11-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_hrstafflist_alter_daterangefilter_parent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HRStaffListTerminations',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('PersNo', models.TextField(blank=True, db_column='PersNo', null=True, verbose_name='PersNo')),
                ('Personnel_Area', models.TextField(blank=True, db_column='Personnel_Area', null=True, verbose_name='Personnel_Area')),
                ('Employee_Group', models.TextField(blank=True, db_column='Employee_Group', null=True, verbose_name='Employee_Group')),
                ('Personnel_Subarea', models.TextField(blank=True, db_column='Personnel_Subarea', null=True, verbose_name='Personnel_Subarea')),
                ('Organizational_Unit', models.TextField(blank=True, db_column='Organizational_Unit', null=True, verbose_name='Organizational_Unit')),
                ('Initials', models.TextField(blank=True, db_column='Initials', null=True, verbose_name='Initials')),
                ('Last_name', models.TextField(blank=True, db_column='Last_name', null=True, verbose_name='Last_name')),
                ('First_name', models.TextField(blank=True, db_column='First_name', null=True, verbose_name='First_name')),
                ('Position', models.TextField(blank=True, db_column='Position', null=True, verbose_name='Position')),
                ('Entry_date', models.BigIntegerField(blank=True, db_column='Entry_date', null=True, verbose_name='Entry_date')),
                ('Termination_date', models.BigIntegerField(blank=True, db_column='Termination_date', null=True, verbose_name='Termination_date')),
                ('loader_instance', models.IntegerField(blank=True, null=True)),
                ('json_data', models.JSONField(blank=True, null=True)),
                ('hash_data', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='daterangefilter',
            name='parent',
            field=models.CharField(choices=[('HR_STAFF_LIST_TERMINATIONS', 'HRStaffListTerminations'), ('HR_STAFF_LIST', 'HRStaffList'), ('FAVORITE', 'Favorite'), ('UNIQUE', 'Unique'), ('FINDING', 'Finding'), ('TAB', 'Tab'), ('COPY_DT', 'Copy DT'), ('FINDING_VIEW', 'Finding View'), ('IMAGE_LOADER', 'Image Loader'), ('IMAGES', 'Images'), ('FINDING_ATTACHMENT', 'Finding Attachment')], max_length=255),
        ),
        migrations.AlterField(
            model_name='floatrangefilter',
            name='parent',
            field=models.CharField(choices=[('HR_STAFF_LIST_TERMINATIONS', 'HRStaffListTerminations'), ('HR_STAFF_LIST', 'HRStaffList'), ('FAVORITE', 'Favorite'), ('UNIQUE', 'Unique'), ('FINDING', 'Finding'), ('TAB', 'Tab'), ('COPY_DT', 'Copy DT'), ('FINDING_VIEW', 'Finding View'), ('IMAGE_LOADER', 'Image Loader'), ('IMAGES', 'Images'), ('FINDING_ATTACHMENT', 'Finding Attachment')], max_length=255),
        ),
        migrations.AlterField(
            model_name='hideshowfilter',
            name='parent',
            field=models.CharField(choices=[('HR_STAFF_LIST_TERMINATIONS', 'HRStaffListTerminations'), ('HR_STAFF_LIST', 'HRStaffList'), ('FAVORITE', 'Favorite'), ('UNIQUE', 'Unique'), ('FINDING', 'Finding'), ('TAB', 'Tab'), ('COPY_DT', 'Copy DT'), ('FINDING_VIEW', 'Finding View'), ('IMAGE_LOADER', 'Image Loader'), ('IMAGES', 'Images'), ('FINDING_ATTACHMENT', 'Finding Attachment')], max_length=255),
        ),
        migrations.AlterField(
            model_name='intrangefilter',
            name='parent',
            field=models.CharField(choices=[('HR_STAFF_LIST_TERMINATIONS', 'HRStaffListTerminations'), ('HR_STAFF_LIST', 'HRStaffList'), ('FAVORITE', 'Favorite'), ('UNIQUE', 'Unique'), ('FINDING', 'Finding'), ('TAB', 'Tab'), ('COPY_DT', 'Copy DT'), ('FINDING_VIEW', 'Finding View'), ('IMAGE_LOADER', 'Image Loader'), ('IMAGES', 'Images'), ('FINDING_ATTACHMENT', 'Finding Attachment')], max_length=255),
        ),
        migrations.AlterField(
            model_name='pageitems',
            name='parent',
            field=models.CharField(choices=[('HR_STAFF_LIST_TERMINATIONS', 'HRStaffListTerminations'), ('HR_STAFF_LIST', 'HRStaffList'), ('FAVORITE', 'Favorite'), ('UNIQUE', 'Unique'), ('FINDING', 'Finding'), ('TAB', 'Tab'), ('COPY_DT', 'Copy DT'), ('FINDING_VIEW', 'Finding View'), ('IMAGE_LOADER', 'Image Loader'), ('IMAGES', 'Images'), ('FINDING_ATTACHMENT', 'Finding Attachment')], max_length=255),
        ),
        migrations.AlterField(
            model_name='selectedrows',
            name='model_choice',
            field=models.CharField(choices=[('HR_STAFF_LIST_TERMINATIONS', 'HRStaffListTerminations'), ('HR_STAFF_LIST', 'HRStaffList'), ('FAVORITE', 'Favorite'), ('UNIQUE', 'Unique'), ('FINDING', 'Finding'), ('TAB', 'Tab'), ('COPY_DT', 'Copy DT'), ('FINDING_VIEW', 'Finding View'), ('IMAGE_LOADER', 'Image Loader'), ('IMAGES', 'Images'), ('FINDING_ATTACHMENT', 'Finding Attachment')], max_length=255),
        ),
        migrations.AlterField(
            model_name='serverfilter',
            name='parent',
            field=models.CharField(choices=[('HR_STAFF_LIST_TERMINATIONS', 'HRStaffListTerminations'), ('HR_STAFF_LIST', 'HRStaffList'), ('FAVORITE', 'Favorite'), ('UNIQUE', 'Unique'), ('FINDING', 'Finding'), ('TAB', 'Tab'), ('COPY_DT', 'Copy DT'), ('FINDING_VIEW', 'Finding View'), ('IMAGE_LOADER', 'Image Loader'), ('IMAGES', 'Images'), ('FINDING_ATTACHMENT', 'Finding Attachment')], max_length=255),
        ),
        migrations.AlterField(
            model_name='userfilter',
            name='parent',
            field=models.CharField(blank=True, choices=[('HR_STAFF_LIST_TERMINATIONS', 'HRStaffListTerminations'), ('HR_STAFF_LIST', 'HRStaffList'), ('FAVORITE', 'Favorite'), ('UNIQUE', 'Unique'), ('FINDING', 'Finding'), ('TAB', 'Tab'), ('COPY_DT', 'Copy DT'), ('FINDING_VIEW', 'Finding View'), ('IMAGE_LOADER', 'Image Loader'), ('IMAGES', 'Images'), ('FINDING_ATTACHMENT', 'Finding Attachment')], max_length=255, null=True),
        ),
    ]
