# Generated by Django 4.2 on 2025-11-21 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0004_hrstafflistterminations_alter_daterangefilter_parent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationUserList',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Full_Name', models.TextField(blank=True, db_column='Full_Name', null=True, verbose_name='Full_Name')),
                ('User_Name', models.TextField(blank=True, db_column='User_Name', null=True, verbose_name='User_Name')),
                ('User_group', models.TextField(blank=True, db_column='User_group', null=True, verbose_name='User_group')),
                ('Valid_From', models.BigIntegerField(blank=True, db_column='Valid_From', null=True, verbose_name='Valid_From')),
                ('Valid_To', models.BigIntegerField(blank=True, db_column='Valid_To', null=True, verbose_name='Valid_To')),
                ('User_Type', models.TextField(blank=True, db_column='User_Type', null=True, verbose_name='User_Type')),
                ('Department', models.TextField(blank=True, db_column='Department', null=True, verbose_name='Department')),
                ('loader_instance', models.IntegerField(blank=True, null=True)),
                ('json_data', models.JSONField(blank=True, null=True)),
                ('hash_data', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='daterangefilter',
            name='parent',
            field=models.CharField(choices=[('APPLICATION_USER_LIST', 'ApplicationUserList'), ('HR_STAFF_LIST_TERMINATIONS', 'HRStaffListTerminations'), ('HR_STAFF_LIST', 'HRStaffList'), ('FAVORITE', 'Favorite'), ('UNIQUE', 'Unique'), ('FINDING', 'Finding'), ('TAB', 'Tab'), ('COPY_DT', 'Copy DT'), ('FINDING_VIEW', 'Finding View'), ('IMAGE_LOADER', 'Image Loader'), ('IMAGES', 'Images'), ('FINDING_ATTACHMENT', 'Finding Attachment')], max_length=255),
        ),
        migrations.AlterField(
            model_name='floatrangefilter',
            name='parent',
            field=models.CharField(choices=[('APPLICATION_USER_LIST', 'ApplicationUserList'), ('HR_STAFF_LIST_TERMINATIONS', 'HRStaffListTerminations'), ('HR_STAFF_LIST', 'HRStaffList'), ('FAVORITE', 'Favorite'), ('UNIQUE', 'Unique'), ('FINDING', 'Finding'), ('TAB', 'Tab'), ('COPY_DT', 'Copy DT'), ('FINDING_VIEW', 'Finding View'), ('IMAGE_LOADER', 'Image Loader'), ('IMAGES', 'Images'), ('FINDING_ATTACHMENT', 'Finding Attachment')], max_length=255),
        ),
        migrations.AlterField(
            model_name='hideshowfilter',
            name='parent',
            field=models.CharField(choices=[('APPLICATION_USER_LIST', 'ApplicationUserList'), ('HR_STAFF_LIST_TERMINATIONS', 'HRStaffListTerminations'), ('HR_STAFF_LIST', 'HRStaffList'), ('FAVORITE', 'Favorite'), ('UNIQUE', 'Unique'), ('FINDING', 'Finding'), ('TAB', 'Tab'), ('COPY_DT', 'Copy DT'), ('FINDING_VIEW', 'Finding View'), ('IMAGE_LOADER', 'Image Loader'), ('IMAGES', 'Images'), ('FINDING_ATTACHMENT', 'Finding Attachment')], max_length=255),
        ),
        migrations.AlterField(
            model_name='intrangefilter',
            name='parent',
            field=models.CharField(choices=[('APPLICATION_USER_LIST', 'ApplicationUserList'), ('HR_STAFF_LIST_TERMINATIONS', 'HRStaffListTerminations'), ('HR_STAFF_LIST', 'HRStaffList'), ('FAVORITE', 'Favorite'), ('UNIQUE', 'Unique'), ('FINDING', 'Finding'), ('TAB', 'Tab'), ('COPY_DT', 'Copy DT'), ('FINDING_VIEW', 'Finding View'), ('IMAGE_LOADER', 'Image Loader'), ('IMAGES', 'Images'), ('FINDING_ATTACHMENT', 'Finding Attachment')], max_length=255),
        ),
        migrations.AlterField(
            model_name='pageitems',
            name='parent',
            field=models.CharField(choices=[('APPLICATION_USER_LIST', 'ApplicationUserList'), ('HR_STAFF_LIST_TERMINATIONS', 'HRStaffListTerminations'), ('HR_STAFF_LIST', 'HRStaffList'), ('FAVORITE', 'Favorite'), ('UNIQUE', 'Unique'), ('FINDING', 'Finding'), ('TAB', 'Tab'), ('COPY_DT', 'Copy DT'), ('FINDING_VIEW', 'Finding View'), ('IMAGE_LOADER', 'Image Loader'), ('IMAGES', 'Images'), ('FINDING_ATTACHMENT', 'Finding Attachment')], max_length=255),
        ),
        migrations.AlterField(
            model_name='selectedrows',
            name='model_choice',
            field=models.CharField(choices=[('APPLICATION_USER_LIST', 'ApplicationUserList'), ('HR_STAFF_LIST_TERMINATIONS', 'HRStaffListTerminations'), ('HR_STAFF_LIST', 'HRStaffList'), ('FAVORITE', 'Favorite'), ('UNIQUE', 'Unique'), ('FINDING', 'Finding'), ('TAB', 'Tab'), ('COPY_DT', 'Copy DT'), ('FINDING_VIEW', 'Finding View'), ('IMAGE_LOADER', 'Image Loader'), ('IMAGES', 'Images'), ('FINDING_ATTACHMENT', 'Finding Attachment')], max_length=255),
        ),
        migrations.AlterField(
            model_name='serverfilter',
            name='parent',
            field=models.CharField(choices=[('APPLICATION_USER_LIST', 'ApplicationUserList'), ('HR_STAFF_LIST_TERMINATIONS', 'HRStaffListTerminations'), ('HR_STAFF_LIST', 'HRStaffList'), ('FAVORITE', 'Favorite'), ('UNIQUE', 'Unique'), ('FINDING', 'Finding'), ('TAB', 'Tab'), ('COPY_DT', 'Copy DT'), ('FINDING_VIEW', 'Finding View'), ('IMAGE_LOADER', 'Image Loader'), ('IMAGES', 'Images'), ('FINDING_ATTACHMENT', 'Finding Attachment')], max_length=255),
        ),
        migrations.AlterField(
            model_name='userfilter',
            name='parent',
            field=models.CharField(blank=True, choices=[('APPLICATION_USER_LIST', 'ApplicationUserList'), ('HR_STAFF_LIST_TERMINATIONS', 'HRStaffListTerminations'), ('HR_STAFF_LIST', 'HRStaffList'), ('FAVORITE', 'Favorite'), ('UNIQUE', 'Unique'), ('FINDING', 'Finding'), ('TAB', 'Tab'), ('COPY_DT', 'Copy DT'), ('FINDING_VIEW', 'Finding View'), ('IMAGE_LOADER', 'Image Loader'), ('IMAGES', 'Images'), ('FINDING_ATTACHMENT', 'Finding Attachment')], max_length=255, null=True),
        ),
    ]
