# Generated by Django 4.2 on 2025-11-21 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0005_applicationuserlist_alter_daterangefilter_parent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HRStaffListVSApplicationUserList',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('PersNo', models.TextField(blank=True, null=True)),
                ('Personnel_Area', models.TextField(blank=True, null=True)),
                ('Employee_Group', models.TextField(blank=True, null=True)),
                ('Personnel_Subarea', models.TextField(blank=True, null=True)),
                ('Organizational_Unit', models.TextField(blank=True, null=True)),
                ('Initials', models.TextField(blank=True, null=True)),
                ('Last_name', models.TextField(blank=True, null=True)),
                ('First_name', models.TextField(blank=True, null=True)),
                ('Position', models.TextField(blank=True, null=True)),
                ('Start_date', models.BigIntegerField(blank=True, null=True)),
                ('Birth_date', models.BigIntegerField(blank=True, null=True)),
                ('d_Full_Name', models.TextField(blank=True, null=True)),
                ('d_User_Name', models.TextField(blank=True, null=True)),
                ('d_User_group', models.TextField(blank=True, null=True)),
                ('d_Valid_From', models.BigIntegerField(blank=True, null=True)),
                ('d_Valid_To', models.BigIntegerField(blank=True, null=True)),
                ('d_User_Type', models.TextField(blank=True, null=True)),
                ('d_Department', models.TextField(blank=True, null=True)),
                ('both', models.IntegerField(blank=True, null=True)),
                ('base', models.IntegerField(blank=True, null=True)),
                ('delta', models.IntegerField(blank=True, null=True)),
                ('loader_instance', models.IntegerField(blank=True, null=True)),
                ('json_data', models.JSONField(blank=True, null=True)),
                ('hash_data', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='daterangefilter',
            name='parent',
            field=models.CharField(choices=[('HR_STAFF_LIST_VS_APPLICATION_USER_LIST', 'HRStaffListVSApplicationUserList'), ('APPLICATION_USER_LIST', 'ApplicationUserList'), ('HR_STAFF_LIST_TERMINATIONS', 'HRStaffListTerminations'), ('HR_STAFF_LIST', 'HRStaffList'), ('FAVORITE', 'Favorite'), ('UNIQUE', 'Unique'), ('FINDING', 'Finding'), ('TAB', 'Tab'), ('COPY_DT', 'Copy DT'), ('FINDING_VIEW', 'Finding View'), ('IMAGE_LOADER', 'Image Loader'), ('IMAGES', 'Images'), ('FINDING_ATTACHMENT', 'Finding Attachment')], max_length=255),
        ),
        migrations.AlterField(
            model_name='floatrangefilter',
            name='parent',
            field=models.CharField(choices=[('HR_STAFF_LIST_VS_APPLICATION_USER_LIST', 'HRStaffListVSApplicationUserList'), ('APPLICATION_USER_LIST', 'ApplicationUserList'), ('HR_STAFF_LIST_TERMINATIONS', 'HRStaffListTerminations'), ('HR_STAFF_LIST', 'HRStaffList'), ('FAVORITE', 'Favorite'), ('UNIQUE', 'Unique'), ('FINDING', 'Finding'), ('TAB', 'Tab'), ('COPY_DT', 'Copy DT'), ('FINDING_VIEW', 'Finding View'), ('IMAGE_LOADER', 'Image Loader'), ('IMAGES', 'Images'), ('FINDING_ATTACHMENT', 'Finding Attachment')], max_length=255),
        ),
        migrations.AlterField(
            model_name='hideshowfilter',
            name='parent',
            field=models.CharField(choices=[('HR_STAFF_LIST_VS_APPLICATION_USER_LIST', 'HRStaffListVSApplicationUserList'), ('APPLICATION_USER_LIST', 'ApplicationUserList'), ('HR_STAFF_LIST_TERMINATIONS', 'HRStaffListTerminations'), ('HR_STAFF_LIST', 'HRStaffList'), ('FAVORITE', 'Favorite'), ('UNIQUE', 'Unique'), ('FINDING', 'Finding'), ('TAB', 'Tab'), ('COPY_DT', 'Copy DT'), ('FINDING_VIEW', 'Finding View'), ('IMAGE_LOADER', 'Image Loader'), ('IMAGES', 'Images'), ('FINDING_ATTACHMENT', 'Finding Attachment')], max_length=255),
        ),
        migrations.AlterField(
            model_name='intrangefilter',
            name='parent',
            field=models.CharField(choices=[('HR_STAFF_LIST_VS_APPLICATION_USER_LIST', 'HRStaffListVSApplicationUserList'), ('APPLICATION_USER_LIST', 'ApplicationUserList'), ('HR_STAFF_LIST_TERMINATIONS', 'HRStaffListTerminations'), ('HR_STAFF_LIST', 'HRStaffList'), ('FAVORITE', 'Favorite'), ('UNIQUE', 'Unique'), ('FINDING', 'Finding'), ('TAB', 'Tab'), ('COPY_DT', 'Copy DT'), ('FINDING_VIEW', 'Finding View'), ('IMAGE_LOADER', 'Image Loader'), ('IMAGES', 'Images'), ('FINDING_ATTACHMENT', 'Finding Attachment')], max_length=255),
        ),
        migrations.AlterField(
            model_name='pageitems',
            name='parent',
            field=models.CharField(choices=[('HR_STAFF_LIST_VS_APPLICATION_USER_LIST', 'HRStaffListVSApplicationUserList'), ('APPLICATION_USER_LIST', 'ApplicationUserList'), ('HR_STAFF_LIST_TERMINATIONS', 'HRStaffListTerminations'), ('HR_STAFF_LIST', 'HRStaffList'), ('FAVORITE', 'Favorite'), ('UNIQUE', 'Unique'), ('FINDING', 'Finding'), ('TAB', 'Tab'), ('COPY_DT', 'Copy DT'), ('FINDING_VIEW', 'Finding View'), ('IMAGE_LOADER', 'Image Loader'), ('IMAGES', 'Images'), ('FINDING_ATTACHMENT', 'Finding Attachment')], max_length=255),
        ),
        migrations.AlterField(
            model_name='selectedrows',
            name='model_choice',
            field=models.CharField(choices=[('HR_STAFF_LIST_VS_APPLICATION_USER_LIST', 'HRStaffListVSApplicationUserList'), ('APPLICATION_USER_LIST', 'ApplicationUserList'), ('HR_STAFF_LIST_TERMINATIONS', 'HRStaffListTerminations'), ('HR_STAFF_LIST', 'HRStaffList'), ('FAVORITE', 'Favorite'), ('UNIQUE', 'Unique'), ('FINDING', 'Finding'), ('TAB', 'Tab'), ('COPY_DT', 'Copy DT'), ('FINDING_VIEW', 'Finding View'), ('IMAGE_LOADER', 'Image Loader'), ('IMAGES', 'Images'), ('FINDING_ATTACHMENT', 'Finding Attachment')], max_length=255),
        ),
        migrations.AlterField(
            model_name='serverfilter',
            name='parent',
            field=models.CharField(choices=[('HR_STAFF_LIST_VS_APPLICATION_USER_LIST', 'HRStaffListVSApplicationUserList'), ('APPLICATION_USER_LIST', 'ApplicationUserList'), ('HR_STAFF_LIST_TERMINATIONS', 'HRStaffListTerminations'), ('HR_STAFF_LIST', 'HRStaffList'), ('FAVORITE', 'Favorite'), ('UNIQUE', 'Unique'), ('FINDING', 'Finding'), ('TAB', 'Tab'), ('COPY_DT', 'Copy DT'), ('FINDING_VIEW', 'Finding View'), ('IMAGE_LOADER', 'Image Loader'), ('IMAGES', 'Images'), ('FINDING_ATTACHMENT', 'Finding Attachment')], max_length=255),
        ),
        migrations.AlterField(
            model_name='userfilter',
            name='parent',
            field=models.CharField(blank=True, choices=[('HR_STAFF_LIST_VS_APPLICATION_USER_LIST', 'HRStaffListVSApplicationUserList'), ('APPLICATION_USER_LIST', 'ApplicationUserList'), ('HR_STAFF_LIST_TERMINATIONS', 'HRStaffListTerminations'), ('HR_STAFF_LIST', 'HRStaffList'), ('FAVORITE', 'Favorite'), ('UNIQUE', 'Unique'), ('FINDING', 'Finding'), ('TAB', 'Tab'), ('COPY_DT', 'Copy DT'), ('FINDING_VIEW', 'Finding View'), ('IMAGE_LOADER', 'Image Loader'), ('IMAGES', 'Images'), ('FINDING_ATTACHMENT', 'Finding Attachment')], max_length=255, null=True),
        ),
    ]
