# Generated by Django 4.2 on 2025-11-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0008_privilegedusers_alter_daterangefilter_parent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisofSecurityAuditsUserLogs',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Creation_Date', models.BigIntegerField(blank=True, db_column='Creation_Date', null=True, verbose_name='Creation_Date')),
                ('Creation_time_of_audit_entry', models.TextField(blank=True, db_column='Creation_time_of_audit_entry', null=True, verbose_name='Creation_time_of_audit_entry')),
                ('Client', models.TextField(blank=True, db_column='Client', null=True, verbose_name='Client')),
                ('User_Name', models.TextField(blank=True, db_column='User_Name', null=True, verbose_name='User_Name')),
                ('Terminal_name', models.TextField(blank=True, db_column='Terminal_name', null=True, verbose_name='Terminal_name')),
                ('Transaction_Code', models.TextField(blank=True, db_column='Transaction_Code', null=True, verbose_name='Transaction_Code')),
                ('Program', models.TextField(blank=True, db_column='Program', null=True, verbose_name='Program')),
                ('Audit_Log_Msg_Text', models.TextField(blank=True, db_column='Audit_Log_Msg_Text', null=True, verbose_name='Audit_Log_Msg_Text')),
                ('Reference_to_Long_Version_of_a_Text', models.TextField(blank=True, db_column='Reference_to_Long_Version_of_a_Text', null=True, verbose_name='Reference_to_Long_Version_of_a_Text')),
                ('SAP_process', models.TextField(blank=True, db_column='SAP_process', null=True, verbose_name='SAP_process')),
                ('Work_Process_Number', models.TextField(blank=True, db_column='Work_Process_Number', null=True, verbose_name='Work_Process_Number')),
                ('Variable_Message_Data', models.TextField(blank=True, db_column='Variable_Message_Data', null=True, verbose_name='Variable_Message_Data')),
                ('loader_instance', models.IntegerField(blank=True, null=True)),
                ('json_data', models.JSONField(blank=True, null=True)),
                ('hash_data', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='daterangefilter',
            name='parent',
            field=models.CharField(choices=[('ANALYSISOF_SECURITY_AUDITS_USER_LOGS', 'AnalysisofSecurityAuditsUserLogs'), ('PRIVILEGEDUSERS', 'Privilegedusers'), ('HR_STAFF_LIST_TERMINATIONS_VS_APPLICATION_USER_LIST', 'HRStaffListTerminationsVSApplicationUserList'), ('HR_STAFF_LIST_VS_APPLICATION_USER_LIST', 'HRStaffListVSApplicationUserList'), ('APPLICATION_USER_LIST', 'ApplicationUserList'), ('HR_STAFF_LIST_TERMINATIONS', 'HRStaffListTerminations'), ('HR_STAFF_LIST', 'HRStaffList'), ('FAVORITE', 'Favorite'), ('UNIQUE', 'Unique'), ('FINDING', 'Finding'), ('TAB', 'Tab'), ('COPY_DT', 'Copy DT'), ('FINDING_VIEW', 'Finding View'), ('IMAGE_LOADER', 'Image Loader'), ('IMAGES', 'Images'), ('FINDING_ATTACHMENT', 'Finding Attachment')], max_length=255),
        ),
        migrations.AlterField(
            model_name='floatrangefilter',
            name='parent',
            field=models.CharField(choices=[('ANALYSISOF_SECURITY_AUDITS_USER_LOGS', 'AnalysisofSecurityAuditsUserLogs'), ('PRIVILEGEDUSERS', 'Privilegedusers'), ('HR_STAFF_LIST_TERMINATIONS_VS_APPLICATION_USER_LIST', 'HRStaffListTerminationsVSApplicationUserList'), ('HR_STAFF_LIST_VS_APPLICATION_USER_LIST', 'HRStaffListVSApplicationUserList'), ('APPLICATION_USER_LIST', 'ApplicationUserList'), ('HR_STAFF_LIST_TERMINATIONS', 'HRStaffListTerminations'), ('HR_STAFF_LIST', 'HRStaffList'), ('FAVORITE', 'Favorite'), ('UNIQUE', 'Unique'), ('FINDING', 'Finding'), ('TAB', 'Tab'), ('COPY_DT', 'Copy DT'), ('FINDING_VIEW', 'Finding View'), ('IMAGE_LOADER', 'Image Loader'), ('IMAGES', 'Images'), ('FINDING_ATTACHMENT', 'Finding Attachment')], max_length=255),
        ),
        migrations.AlterField(
            model_name='hideshowfilter',
            name='parent',
            field=models.CharField(choices=[('ANALYSISOF_SECURITY_AUDITS_USER_LOGS', 'AnalysisofSecurityAuditsUserLogs'), ('PRIVILEGEDUSERS', 'Privilegedusers'), ('HR_STAFF_LIST_TERMINATIONS_VS_APPLICATION_USER_LIST', 'HRStaffListTerminationsVSApplicationUserList'), ('HR_STAFF_LIST_VS_APPLICATION_USER_LIST', 'HRStaffListVSApplicationUserList'), ('APPLICATION_USER_LIST', 'ApplicationUserList'), ('HR_STAFF_LIST_TERMINATIONS', 'HRStaffListTerminations'), ('HR_STAFF_LIST', 'HRStaffList'), ('FAVORITE', 'Favorite'), ('UNIQUE', 'Unique'), ('FINDING', 'Finding'), ('TAB', 'Tab'), ('COPY_DT', 'Copy DT'), ('FINDING_VIEW', 'Finding View'), ('IMAGE_LOADER', 'Image Loader'), ('IMAGES', 'Images'), ('FINDING_ATTACHMENT', 'Finding Attachment')], max_length=255),
        ),
        migrations.AlterField(
            model_name='intrangefilter',
            name='parent',
            field=models.CharField(choices=[('ANALYSISOF_SECURITY_AUDITS_USER_LOGS', 'AnalysisofSecurityAuditsUserLogs'), ('PRIVILEGEDUSERS', 'Privilegedusers'), ('HR_STAFF_LIST_TERMINATIONS_VS_APPLICATION_USER_LIST', 'HRStaffListTerminationsVSApplicationUserList'), ('HR_STAFF_LIST_VS_APPLICATION_USER_LIST', 'HRStaffListVSApplicationUserList'), ('APPLICATION_USER_LIST', 'ApplicationUserList'), ('HR_STAFF_LIST_TERMINATIONS', 'HRStaffListTerminations'), ('HR_STAFF_LIST', 'HRStaffList'), ('FAVORITE', 'Favorite'), ('UNIQUE', 'Unique'), ('FINDING', 'Finding'), ('TAB', 'Tab'), ('COPY_DT', 'Copy DT'), ('FINDING_VIEW', 'Finding View'), ('IMAGE_LOADER', 'Image Loader'), ('IMAGES', 'Images'), ('FINDING_ATTACHMENT', 'Finding Attachment')], max_length=255),
        ),
        migrations.AlterField(
            model_name='pageitems',
            name='parent',
            field=models.CharField(choices=[('ANALYSISOF_SECURITY_AUDITS_USER_LOGS', 'AnalysisofSecurityAuditsUserLogs'), ('PRIVILEGEDUSERS', 'Privilegedusers'), ('HR_STAFF_LIST_TERMINATIONS_VS_APPLICATION_USER_LIST', 'HRStaffListTerminationsVSApplicationUserList'), ('HR_STAFF_LIST_VS_APPLICATION_USER_LIST', 'HRStaffListVSApplicationUserList'), ('APPLICATION_USER_LIST', 'ApplicationUserList'), ('HR_STAFF_LIST_TERMINATIONS', 'HRStaffListTerminations'), ('HR_STAFF_LIST', 'HRStaffList'), ('FAVORITE', 'Favorite'), ('UNIQUE', 'Unique'), ('FINDING', 'Finding'), ('TAB', 'Tab'), ('COPY_DT', 'Copy DT'), ('FINDING_VIEW', 'Finding View'), ('IMAGE_LOADER', 'Image Loader'), ('IMAGES', 'Images'), ('FINDING_ATTACHMENT', 'Finding Attachment')], max_length=255),
        ),
        migrations.AlterField(
            model_name='selectedrows',
            name='model_choice',
            field=models.CharField(choices=[('ANALYSISOF_SECURITY_AUDITS_USER_LOGS', 'AnalysisofSecurityAuditsUserLogs'), ('PRIVILEGEDUSERS', 'Privilegedusers'), ('HR_STAFF_LIST_TERMINATIONS_VS_APPLICATION_USER_LIST', 'HRStaffListTerminationsVSApplicationUserList'), ('HR_STAFF_LIST_VS_APPLICATION_USER_LIST', 'HRStaffListVSApplicationUserList'), ('APPLICATION_USER_LIST', 'ApplicationUserList'), ('HR_STAFF_LIST_TERMINATIONS', 'HRStaffListTerminations'), ('HR_STAFF_LIST', 'HRStaffList'), ('FAVORITE', 'Favorite'), ('UNIQUE', 'Unique'), ('FINDING', 'Finding'), ('TAB', 'Tab'), ('COPY_DT', 'Copy DT'), ('FINDING_VIEW', 'Finding View'), ('IMAGE_LOADER', 'Image Loader'), ('IMAGES', 'Images'), ('FINDING_ATTACHMENT', 'Finding Attachment')], max_length=255),
        ),
        migrations.AlterField(
            model_name='serverfilter',
            name='parent',
            field=models.CharField(choices=[('ANALYSISOF_SECURITY_AUDITS_USER_LOGS', 'AnalysisofSecurityAuditsUserLogs'), ('PRIVILEGEDUSERS', 'Privilegedusers'), ('HR_STAFF_LIST_TERMINATIONS_VS_APPLICATION_USER_LIST', 'HRStaffListTerminationsVSApplicationUserList'), ('HR_STAFF_LIST_VS_APPLICATION_USER_LIST', 'HRStaffListVSApplicationUserList'), ('APPLICATION_USER_LIST', 'ApplicationUserList'), ('HR_STAFF_LIST_TERMINATIONS', 'HRStaffListTerminations'), ('HR_STAFF_LIST', 'HRStaffList'), ('FAVORITE', 'Favorite'), ('UNIQUE', 'Unique'), ('FINDING', 'Finding'), ('TAB', 'Tab'), ('COPY_DT', 'Copy DT'), ('FINDING_VIEW', 'Finding View'), ('IMAGE_LOADER', 'Image Loader'), ('IMAGES', 'Images'), ('FINDING_ATTACHMENT', 'Finding Attachment')], max_length=255),
        ),
        migrations.AlterField(
            model_name='userfilter',
            name='parent',
            field=models.CharField(blank=True, choices=[('ANALYSISOF_SECURITY_AUDITS_USER_LOGS', 'AnalysisofSecurityAuditsUserLogs'), ('PRIVILEGEDUSERS', 'Privilegedusers'), ('HR_STAFF_LIST_TERMINATIONS_VS_APPLICATION_USER_LIST', 'HRStaffListTerminationsVSApplicationUserList'), ('HR_STAFF_LIST_VS_APPLICATION_USER_LIST', 'HRStaffListVSApplicationUserList'), ('APPLICATION_USER_LIST', 'ApplicationUserList'), ('HR_STAFF_LIST_TERMINATIONS', 'HRStaffListTerminations'), ('HR_STAFF_LIST', 'HRStaffList'), ('FAVORITE', 'Favorite'), ('UNIQUE', 'Unique'), ('FINDING', 'Finding'), ('TAB', 'Tab'), ('COPY_DT', 'Copy DT'), ('FINDING_VIEW', 'Finding View'), ('IMAGE_LOADER', 'Image Loader'), ('IMAGES', 'Images'), ('FINDING_ATTACHMENT', 'Finding Attachment')], max_length=255, null=True),
        ),
    ]
