# Generated by Django 4.2 on 2025-11-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0009_analysisofsecurityauditsuserlogs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivilegedusersVsUserLogs',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('User_Name', models.TextField(blank=True, null=True)),
                ('Full_Name', models.TextField(blank=True, null=True)),
                ('User_group', models.TextField(blank=True, null=True)),
                ('Locked', models.TextField(blank=True, null=True)),
                ('Reason_for_User_Lock', models.TextField(blank=True, null=True)),
                ('Valid_From', models.BigIntegerField(blank=True, null=True)),
                ('Valid_To', models.BigIntegerField(blank=True, null=True)),
                ('User_Type', models.TextField(blank=True, null=True)),
                ('Department', models.TextField(blank=True, null=True)),
                ('d_Creation_Date', models.BigIntegerField(blank=True, null=True)),
                ('d_Creation_time_of_audit_entry', models.TextField(blank=True, null=True)),
                ('d_Client', models.TextField(blank=True, null=True)),
                ('d_User_Name', models.TextField(blank=True, null=True)),
                ('d_Terminal_name', models.TextField(blank=True, null=True)),
                ('d_Transaction_Code', models.TextField(blank=True, null=True)),
                ('d_Program', models.TextField(blank=True, null=True)),
                ('d_Audit_Log_Msg_Text', models.TextField(blank=True, null=True)),
                ('d_Reference_to_Long_Version_of_a_Text', models.TextField(blank=True, null=True)),
                ('d_SAP_process', models.TextField(blank=True, null=True)),
                ('d_Work_Process_Number', models.TextField(blank=True, null=True)),
                ('d_Variable_Message_Data', models.TextField(blank=True, null=True)),
                ('both', models.IntegerField(blank=True, null=True)),
                ('base', models.IntegerField(blank=True, null=True)),
                ('delta', models.IntegerField(blank=True, null=True)),
                ('loader_instance', models.IntegerField(blank=True, null=True)),
                ('json_data', models.JSONField(blank=True, null=True)),
                ('hash_data', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='daterangefilter',
            name='parent',
            field=models.CharField(choices=[('PRIVILEGEDUSERS_VS_USER_LOGS', 'PrivilegedusersVsUserLogs'), ('ANALYSISOF_SECURITY_AUDITS_USER_LOGS', 'AnalysisofSecurityAuditsUserLogs'), ('PRIVILEGEDUSERS', 'Privilegedusers'), ('HR_STAFF_LIST_TERMINATIONS_VS_APPLICATION_USER_LIST', 'HRStaffListTerminationsVSApplicationUserList'), ('HR_STAFF_LIST_VS_APPLICATION_USER_LIST', 'HRStaffListVSApplicationUserList'), ('APPLICATION_USER_LIST', 'ApplicationUserList'), ('HR_STAFF_LIST_TERMINATIONS', 'HRStaffListTerminations'), ('HR_STAFF_LIST', 'HRStaffList'), ('FAVORITE', 'Favorite'), ('UNIQUE', 'Unique'), ('FINDING', 'Finding'), ('TAB', 'Tab'), ('COPY_DT', 'Copy DT'), ('FINDING_VIEW', 'Finding View'), ('IMAGE_LOADER', 'Image Loader'), ('IMAGES', 'Images'), ('FINDING_ATTACHMENT', 'Finding Attachment')], max_length=255),
        ),
        migrations.AlterField(
            model_name='floatrangefilter',
            name='parent',
            field=models.CharField(choices=[('PRIVILEGEDUSERS_VS_USER_LOGS', 'PrivilegedusersVsUserLogs'), ('ANALYSISOF_SECURITY_AUDITS_USER_LOGS', 'AnalysisofSecurityAuditsUserLogs'), ('PRIVILEGEDUSERS', 'Privilegedusers'), ('HR_STAFF_LIST_TERMINATIONS_VS_APPLICATION_USER_LIST', 'HRStaffListTerminationsVSApplicationUserList'), ('HR_STAFF_LIST_VS_APPLICATION_USER_LIST', 'HRStaffListVSApplicationUserList'), ('APPLICATION_USER_LIST', 'ApplicationUserList'), ('HR_STAFF_LIST_TERMINATIONS', 'HRStaffListTerminations'), ('HR_STAFF_LIST', 'HRStaffList'), ('FAVORITE', 'Favorite'), ('UNIQUE', 'Unique'), ('FINDING', 'Finding'), ('TAB', 'Tab'), ('COPY_DT', 'Copy DT'), ('FINDING_VIEW', 'Finding View'), ('IMAGE_LOADER', 'Image Loader'), ('IMAGES', 'Images'), ('FINDING_ATTACHMENT', 'Finding Attachment')], max_length=255),
        ),
        migrations.AlterField(
            model_name='hideshowfilter',
            name='parent',
            field=models.CharField(choices=[('PRIVILEGEDUSERS_VS_USER_LOGS', 'PrivilegedusersVsUserLogs'), ('ANALYSISOF_SECURITY_AUDITS_USER_LOGS', 'AnalysisofSecurityAuditsUserLogs'), ('PRIVILEGEDUSERS', 'Privilegedusers'), ('HR_STAFF_LIST_TERMINATIONS_VS_APPLICATION_USER_LIST', 'HRStaffListTerminationsVSApplicationUserList'), ('HR_STAFF_LIST_VS_APPLICATION_USER_LIST', 'HRStaffListVSApplicationUserList'), ('APPLICATION_USER_LIST', 'ApplicationUserList'), ('HR_STAFF_LIST_TERMINATIONS', 'HRStaffListTerminations'), ('HR_STAFF_LIST', 'HRStaffList'), ('FAVORITE', 'Favorite'), ('UNIQUE', 'Unique'), ('FINDING', 'Finding'), ('TAB', 'Tab'), ('COPY_DT', 'Copy DT'), ('FINDING_VIEW', 'Finding View'), ('IMAGE_LOADER', 'Image Loader'), ('IMAGES', 'Images'), ('FINDING_ATTACHMENT', 'Finding Attachment')], max_length=255),
        ),
        migrations.AlterField(
            model_name='intrangefilter',
            name='parent',
            field=models.CharField(choices=[('PRIVILEGEDUSERS_VS_USER_LOGS', 'PrivilegedusersVsUserLogs'), ('ANALYSISOF_SECURITY_AUDITS_USER_LOGS', 'AnalysisofSecurityAuditsUserLogs'), ('PRIVILEGEDUSERS', 'Privilegedusers'), ('HR_STAFF_LIST_TERMINATIONS_VS_APPLICATION_USER_LIST', 'HRStaffListTerminationsVSApplicationUserList'), ('HR_STAFF_LIST_VS_APPLICATION_USER_LIST', 'HRStaffListVSApplicationUserList'), ('APPLICATION_USER_LIST', 'ApplicationUserList'), ('HR_STAFF_LIST_TERMINATIONS', 'HRStaffListTerminations'), ('HR_STAFF_LIST', 'HRStaffList'), ('FAVORITE', 'Favorite'), ('UNIQUE', 'Unique'), ('FINDING', 'Finding'), ('TAB', 'Tab'), ('COPY_DT', 'Copy DT'), ('FINDING_VIEW', 'Finding View'), ('IMAGE_LOADER', 'Image Loader'), ('IMAGES', 'Images'), ('FINDING_ATTACHMENT', 'Finding Attachment')], max_length=255),
        ),
        migrations.AlterField(
            model_name='pageitems',
            name='parent',
            field=models.CharField(choices=[('PRIVILEGEDUSERS_VS_USER_LOGS', 'PrivilegedusersVsUserLogs'), ('ANALYSISOF_SECURITY_AUDITS_USER_LOGS', 'AnalysisofSecurityAuditsUserLogs'), ('PRIVILEGEDUSERS', 'Privilegedusers'), ('HR_STAFF_LIST_TERMINATIONS_VS_APPLICATION_USER_LIST', 'HRStaffListTerminationsVSApplicationUserList'), ('HR_STAFF_LIST_VS_APPLICATION_USER_LIST', 'HRStaffListVSApplicationUserList'), ('APPLICATION_USER_LIST', 'ApplicationUserList'), ('HR_STAFF_LIST_TERMINATIONS', 'HRStaffListTerminations'), ('HR_STAFF_LIST', 'HRStaffList'), ('FAVORITE', 'Favorite'), ('UNIQUE', 'Unique'), ('FINDING', 'Finding'), ('TAB', 'Tab'), ('COPY_DT', 'Copy DT'), ('FINDING_VIEW', 'Finding View'), ('IMAGE_LOADER', 'Image Loader'), ('IMAGES', 'Images'), ('FINDING_ATTACHMENT', 'Finding Attachment')], max_length=255),
        ),
        migrations.AlterField(
            model_name='selectedrows',
            name='model_choice',
            field=models.CharField(choices=[('PRIVILEGEDUSERS_VS_USER_LOGS', 'PrivilegedusersVsUserLogs'), ('ANALYSISOF_SECURITY_AUDITS_USER_LOGS', 'AnalysisofSecurityAuditsUserLogs'), ('PRIVILEGEDUSERS', 'Privilegedusers'), ('HR_STAFF_LIST_TERMINATIONS_VS_APPLICATION_USER_LIST', 'HRStaffListTerminationsVSApplicationUserList'), ('HR_STAFF_LIST_VS_APPLICATION_USER_LIST', 'HRStaffListVSApplicationUserList'), ('APPLICATION_USER_LIST', 'ApplicationUserList'), ('HR_STAFF_LIST_TERMINATIONS', 'HRStaffListTerminations'), ('HR_STAFF_LIST', 'HRStaffList'), ('FAVORITE', 'Favorite'), ('UNIQUE', 'Unique'), ('FINDING', 'Finding'), ('TAB', 'Tab'), ('COPY_DT', 'Copy DT'), ('FINDING_VIEW', 'Finding View'), ('IMAGE_LOADER', 'Image Loader'), ('IMAGES', 'Images'), ('FINDING_ATTACHMENT', 'Finding Attachment')], max_length=255),
        ),
        migrations.AlterField(
            model_name='serverfilter',
            name='parent',
            field=models.CharField(choices=[('PRIVILEGEDUSERS_VS_USER_LOGS', 'PrivilegedusersVsUserLogs'), ('ANALYSISOF_SECURITY_AUDITS_USER_LOGS', 'AnalysisofSecurityAuditsUserLogs'), ('PRIVILEGEDUSERS', 'Privilegedusers'), ('HR_STAFF_LIST_TERMINATIONS_VS_APPLICATION_USER_LIST', 'HRStaffListTerminationsVSApplicationUserList'), ('HR_STAFF_LIST_VS_APPLICATION_USER_LIST', 'HRStaffListVSApplicationUserList'), ('APPLICATION_USER_LIST', 'ApplicationUserList'), ('HR_STAFF_LIST_TERMINATIONS', 'HRStaffListTerminations'), ('HR_STAFF_LIST', 'HRStaffList'), ('FAVORITE', 'Favorite'), ('UNIQUE', 'Unique'), ('FINDING', 'Finding'), ('TAB', 'Tab'), ('COPY_DT', 'Copy DT'), ('FINDING_VIEW', 'Finding View'), ('IMAGE_LOADER', 'Image Loader'), ('IMAGES', 'Images'), ('FINDING_ATTACHMENT', 'Finding Attachment')], max_length=255),
        ),
        migrations.AlterField(
            model_name='userfilter',
            name='parent',
            field=models.CharField(blank=True, choices=[('PRIVILEGEDUSERS_VS_USER_LOGS', 'PrivilegedusersVsUserLogs'), ('ANALYSISOF_SECURITY_AUDITS_USER_LOGS', 'AnalysisofSecurityAuditsUserLogs'), ('PRIVILEGEDUSERS', 'Privilegedusers'), ('HR_STAFF_LIST_TERMINATIONS_VS_APPLICATION_USER_LIST', 'HRStaffListTerminationsVSApplicationUserList'), ('HR_STAFF_LIST_VS_APPLICATION_USER_LIST', 'HRStaffListVSApplicationUserList'), ('APPLICATION_USER_LIST', 'ApplicationUserList'), ('HR_STAFF_LIST_TERMINATIONS', 'HRStaffListTerminations'), ('HR_STAFF_LIST', 'HRStaffList'), ('FAVORITE', 'Favorite'), ('UNIQUE', 'Unique'), ('FINDING', 'Finding'), ('TAB', 'Tab'), ('COPY_DT', 'Copy DT'), ('FINDING_VIEW', 'Finding View'), ('IMAGE_LOADER', 'Image Loader'), ('IMAGES', 'Images'), ('FINDING_ATTACHMENT', 'Finding Attachment')], max_length=255, null=True),
        ),
    ]
