# Generated by Django 4.2 on 2025-11-26 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0010_privilegedusersvsuserlogs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLogsVsPrivilegedusers',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Creation_Date', models.BigIntegerField(blank=True, null=True)),
                ('Creation_time_of_audit_entry', models.TextField(blank=True, null=True)),
                ('Client', models.TextField(blank=True, null=True)),
                ('User_Name', models.TextField(blank=True, null=True)),
                ('Terminal_name', models.TextField(blank=True, null=True)),
                ('Transaction_Code', models.TextField(blank=True, null=True)),
                ('Program', models.TextField(blank=True, null=True)),
                ('Audit_Log_Msg_Text', models.TextField(blank=True, null=True)),
                ('Reference_to_Long_Version_of_a_Text', models.TextField(blank=True, null=True)),
                ('SAP_process', models.TextField(blank=True, null=True)),
                ('Work_Process_Number', models.TextField(blank=True, null=True)),
                ('Variable_Message_Data', models.TextField(blank=True, null=True)),
                ('d_User_Name', models.TextField(blank=True, null=True)),
                ('d_Full_Name', models.TextField(blank=True, null=True)),
                ('d_User_group', models.TextField(blank=True, null=True)),
                ('d_Locked', models.TextField(blank=True, null=True)),
                ('d_Reason_for_User_Lock', models.TextField(blank=True, null=True)),
                ('d_Valid_From', models.BigIntegerField(blank=True, null=True)),
                ('d_Valid_To', models.BigIntegerField(blank=True, null=True)),
                ('d_User_Type', models.TextField(blank=True, null=True)),
                ('d_Department', models.TextField(blank=True, null=True)),
                ('both', models.IntegerField(blank=True, null=True)),
                ('base', models.IntegerField(blank=True, null=True)),
                ('delta', models.IntegerField(blank=True, null=True)),
                ('loader_instance', models.IntegerField(blank=True, null=True)),
                ('json_data', models.JSONField(blank=True, null=True)),
                ('hash_data', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='daterangefilter',
            name='parent',
            field=models.CharField(choices=[('USER_LOGS_VS_PRIVILEGEDUSERS', 'UserLogsVsPrivilegedusers'), ('PRIVILEGEDUSERS_VS_USER_LOGS', 'PrivilegedusersVsUserLogs'), ('ANALYSISOF_SECURITY_AUDITS_USER_LOGS', 'AnalysisofSecurityAuditsUserLogs'), ('PRIVILEGEDUSERS', 'Privilegedusers'), ('HR_STAFF_LIST_TERMINATIONS_VS_APPLICATION_USER_LIST', 'HRStaffListTerminationsVSApplicationUserList'), ('HR_STAFF_LIST_VS_APPLICATION_USER_LIST', 'HRStaffListVSApplicationUserList'), ('APPLICATION_USER_LIST', 'ApplicationUserList'), ('HR_STAFF_LIST_TERMINATIONS', 'HRStaffListTerminations'), ('HR_STAFF_LIST', 'HRStaffList'), ('FAVORITE', 'Favorite'), ('UNIQUE', 'Unique'), ('FINDING', 'Finding'), ('TAB', 'Tab'), ('COPY_DT', 'Copy DT'), ('FINDING_VIEW', 'Finding View'), ('IMAGE_LOADER', 'Image Loader'), ('IMAGES', 'Images'), ('FINDING_ATTACHMENT', 'Finding Attachment')], max_length=255),
        ),
        migrations.AlterField(
            model_name='floatrangefilter',
            name='parent',
            field=models.CharField(choices=[('USER_LOGS_VS_PRIVILEGEDUSERS', 'UserLogsVsPrivilegedusers'), ('PRIVILEGEDUSERS_VS_USER_LOGS', 'PrivilegedusersVsUserLogs'), ('ANALYSISOF_SECURITY_AUDITS_USER_LOGS', 'AnalysisofSecurityAuditsUserLogs'), ('PRIVILEGEDUSERS', 'Privilegedusers'), ('HR_STAFF_LIST_TERMINATIONS_VS_APPLICATION_USER_LIST', 'HRStaffListTerminationsVSApplicationUserList'), ('HR_STAFF_LIST_VS_APPLICATION_USER_LIST', 'HRStaffListVSApplicationUserList'), ('APPLICATION_USER_LIST', 'ApplicationUserList'), ('HR_STAFF_LIST_TERMINATIONS', 'HRStaffListTerminations'), ('HR_STAFF_LIST', 'HRStaffList'), ('FAVORITE', 'Favorite'), ('UNIQUE', 'Unique'), ('FINDING', 'Finding'), ('TAB', 'Tab'), ('COPY_DT', 'Copy DT'), ('FINDING_VIEW', 'Finding View'), ('IMAGE_LOADER', 'Image Loader'), ('IMAGES', 'Images'), ('FINDING_ATTACHMENT', 'Finding Attachment')], max_length=255),
        ),
        migrations.AlterField(
            model_name='hideshowfilter',
            name='parent',
            field=models.CharField(choices=[('USER_LOGS_VS_PRIVILEGEDUSERS', 'UserLogsVsPrivilegedusers'), ('PRIVILEGEDUSERS_VS_USER_LOGS', 'PrivilegedusersVsUserLogs'), ('ANALYSISOF_SECURITY_AUDITS_USER_LOGS', 'AnalysisofSecurityAuditsUserLogs'), ('PRIVILEGEDUSERS', 'Privilegedusers'), ('HR_STAFF_LIST_TERMINATIONS_VS_APPLICATION_USER_LIST', 'HRStaffListTerminationsVSApplicationUserList'), ('HR_STAFF_LIST_VS_APPLICATION_USER_LIST', 'HRStaffListVSApplicationUserList'), ('APPLICATION_USER_LIST', 'ApplicationUserList'), ('HR_STAFF_LIST_TERMINATIONS', 'HRStaffListTerminations'), ('HR_STAFF_LIST', 'HRStaffList'), ('FAVORITE', 'Favorite'), ('UNIQUE', 'Unique'), ('FINDING', 'Finding'), ('TAB', 'Tab'), ('COPY_DT', 'Copy DT'), ('FINDING_VIEW', 'Finding View'), ('IMAGE_LOADER', 'Image Loader'), ('IMAGES', 'Images'), ('FINDING_ATTACHMENT', 'Finding Attachment')], max_length=255),
        ),
        migrations.AlterField(
            model_name='intrangefilter',
            name='parent',
            field=models.CharField(choices=[('USER_LOGS_VS_PRIVILEGEDUSERS', 'UserLogsVsPrivilegedusers'), ('PRIVILEGEDUSERS_VS_USER_LOGS', 'PrivilegedusersVsUserLogs'), ('ANALYSISOF_SECURITY_AUDITS_USER_LOGS', 'AnalysisofSecurityAuditsUserLogs'), ('PRIVILEGEDUSERS', 'Privilegedusers'), ('HR_STAFF_LIST_TERMINATIONS_VS_APPLICATION_USER_LIST', 'HRStaffListTerminationsVSApplicationUserList'), ('HR_STAFF_LIST_VS_APPLICATION_USER_LIST', 'HRStaffListVSApplicationUserList'), ('APPLICATION_USER_LIST', 'ApplicationUserList'), ('HR_STAFF_LIST_TERMINATIONS', 'HRStaffListTerminations'), ('HR_STAFF_LIST', 'HRStaffList'), ('FAVORITE', 'Favorite'), ('UNIQUE', 'Unique'), ('FINDING', 'Finding'), ('TAB', 'Tab'), ('COPY_DT', 'Copy DT'), ('FINDING_VIEW', 'Finding View'), ('IMAGE_LOADER', 'Image Loader'), ('IMAGES', 'Images'), ('FINDING_ATTACHMENT', 'Finding Attachment')], max_length=255),
        ),
        migrations.AlterField(
            model_name='pageitems',
            name='parent',
            field=models.CharField(choices=[('USER_LOGS_VS_PRIVILEGEDUSERS', 'UserLogsVsPrivilegedusers'), ('PRIVILEGEDUSERS_VS_USER_LOGS', 'PrivilegedusersVsUserLogs'), ('ANALYSISOF_SECURITY_AUDITS_USER_LOGS', 'AnalysisofSecurityAuditsUserLogs'), ('PRIVILEGEDUSERS', 'Privilegedusers'), ('HR_STAFF_LIST_TERMINATIONS_VS_APPLICATION_USER_LIST', 'HRStaffListTerminationsVSApplicationUserList'), ('HR_STAFF_LIST_VS_APPLICATION_USER_LIST', 'HRStaffListVSApplicationUserList'), ('APPLICATION_USER_LIST', 'ApplicationUserList'), ('HR_STAFF_LIST_TERMINATIONS', 'HRStaffListTerminations'), ('HR_STAFF_LIST', 'HRStaffList'), ('FAVORITE', 'Favorite'), ('UNIQUE', 'Unique'), ('FINDING', 'Finding'), ('TAB', 'Tab'), ('COPY_DT', 'Copy DT'), ('FINDING_VIEW', 'Finding View'), ('IMAGE_LOADER', 'Image Loader'), ('IMAGES', 'Images'), ('FINDING_ATTACHMENT', 'Finding Attachment')], max_length=255),
        ),
        migrations.AlterField(
            model_name='selectedrows',
            name='model_choice',
            field=models.CharField(choices=[('USER_LOGS_VS_PRIVILEGEDUSERS', 'UserLogsVsPrivilegedusers'), ('PRIVILEGEDUSERS_VS_USER_LOGS', 'PrivilegedusersVsUserLogs'), ('ANALYSISOF_SECURITY_AUDITS_USER_LOGS', 'AnalysisofSecurityAuditsUserLogs'), ('PRIVILEGEDUSERS', 'Privilegedusers'), ('HR_STAFF_LIST_TERMINATIONS_VS_APPLICATION_USER_LIST', 'HRStaffListTerminationsVSApplicationUserList'), ('HR_STAFF_LIST_VS_APPLICATION_USER_LIST', 'HRStaffListVSApplicationUserList'), ('APPLICATION_USER_LIST', 'ApplicationUserList'), ('HR_STAFF_LIST_TERMINATIONS', 'HRStaffListTerminations'), ('HR_STAFF_LIST', 'HRStaffList'), ('FAVORITE', 'Favorite'), ('UNIQUE', 'Unique'), ('FINDING', 'Finding'), ('TAB', 'Tab'), ('COPY_DT', 'Copy DT'), ('FINDING_VIEW', 'Finding View'), ('IMAGE_LOADER', 'Image Loader'), ('IMAGES', 'Images'), ('FINDING_ATTACHMENT', 'Finding Attachment')], max_length=255),
        ),
        migrations.AlterField(
            model_name='serverfilter',
            name='parent',
            field=models.CharField(choices=[('USER_LOGS_VS_PRIVILEGEDUSERS', 'UserLogsVsPrivilegedusers'), ('PRIVILEGEDUSERS_VS_USER_LOGS', 'PrivilegedusersVsUserLogs'), ('ANALYSISOF_SECURITY_AUDITS_USER_LOGS', 'AnalysisofSecurityAuditsUserLogs'), ('PRIVILEGEDUSERS', 'Privilegedusers'), ('HR_STAFF_LIST_TERMINATIONS_VS_APPLICATION_USER_LIST', 'HRStaffListTerminationsVSApplicationUserList'), ('HR_STAFF_LIST_VS_APPLICATION_USER_LIST', 'HRStaffListVSApplicationUserList'), ('APPLICATION_USER_LIST', 'ApplicationUserList'), ('HR_STAFF_LIST_TERMINATIONS', 'HRStaffListTerminations'), ('HR_STAFF_LIST', 'HRStaffList'), ('FAVORITE', 'Favorite'), ('UNIQUE', 'Unique'), ('FINDING', 'Finding'), ('TAB', 'Tab'), ('COPY_DT', 'Copy DT'), ('FINDING_VIEW', 'Finding View'), ('IMAGE_LOADER', 'Image Loader'), ('IMAGES', 'Images'), ('FINDING_ATTACHMENT', 'Finding Attachment')], max_length=255),
        ),
        migrations.AlterField(
            model_name='userfilter',
            name='parent',
            field=models.CharField(blank=True, choices=[('USER_LOGS_VS_PRIVILEGEDUSERS', 'UserLogsVsPrivilegedusers'), ('PRIVILEGEDUSERS_VS_USER_LOGS', 'PrivilegedusersVsUserLogs'), ('ANALYSISOF_SECURITY_AUDITS_USER_LOGS', 'AnalysisofSecurityAuditsUserLogs'), ('PRIVILEGEDUSERS', 'Privilegedusers'), ('HR_STAFF_LIST_TERMINATIONS_VS_APPLICATION_USER_LIST', 'HRStaffListTerminationsVSApplicationUserList'), ('HR_STAFF_LIST_VS_APPLICATION_USER_LIST', 'HRStaffListVSApplicationUserList'), ('APPLICATION_USER_LIST', 'ApplicationUserList'), ('HR_STAFF_LIST_TERMINATIONS', 'HRStaffListTerminations'), ('HR_STAFF_LIST', 'HRStaffList'), ('FAVORITE', 'Favorite'), ('UNIQUE', 'Unique'), ('FINDING', 'Finding'), ('TAB', 'Tab'), ('COPY_DT', 'Copy DT'), ('FINDING_VIEW', 'Finding View'), ('IMAGE_LOADER', 'Image Loader'), ('IMAGES', 'Images'), ('FINDING_ATTACHMENT', 'Finding Attachment')], max_length=255, null=True),
        ),
    ]
