# Generated by Django 4.2 on 2025-11-14 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=100)),
                ('column_order', models.JSONField()),
                ('favorite_id', models.TextField(blank=True, null=True)),
                ('finding_id', models.TextField(blank=True, null=True)),
                ('img_loader_id', models.TextField(blank=True, null=True)),
                ('unique_id', models.TextField(blank=True, null=True)),
                ('tab_id', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.URLField()),
                ('info', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='IPE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.CharField(blank=True, choices=[('ADSDELTA_LICENSED_VS_ANTI_VIRUS_TEST', 'ADSDELTALicensedVsAntiVirusTest'), ('ADSDELTA_LICENSEDVS_ANTI_VIRUS', 'ADSDELTALicensedvsAntiVirus'), ('ASTEALICENSEUSERS', 'Astealicenseusers'), ('ADSASEC_ANTIVIRUS_F', 'ADSASECAntivirusF'), ('ADS_DEFENDER_F', 'ADSDefenderF'), ('ADSASEC_ANTIVIRUS', 'ADSASECAntivirus'), ('ADS_DEFENDER_AGENTS', 'ADSDefenderAgents'), ('DELTAADS_LICENSESVS_AD', 'DELTAADSLicensesvsAD'), ('FINTECH_NEW_USER_AD', 'FintechNewUserAD'), ('FINTECH_NEW_SYSPRO_OPERATOR_LIST', 'FintechNewSysproOperatorList'), ('FINTECH_NEW_STAFF_LISTING', 'FintechNewStaffListing'), ('FINTECH_NEW_ENTRA_REPORT', 'FintechNewEntraReport'), ('DELTA_FINTECH_NEW_NEWUSERS_SYSPROTO_HR_MASTER', 'DeltaFintechNewNewusersSysprotoHRMaster'), ('ADS_DELTA_A_DVS_HR', 'ADSDeltaADvsHR'), ('DELTA_FINTECH_NEW_SYSPROVS_A_DUSERS', 'DeltaFintechNewSysprovsADusers'), ('USERADMEMBERSHIPS_FINTEC', 'UseradmembershipsFintec'), ('USERAD_FINTECH', 'UseradFintech'), ('SYSP_OPERATOR_LISTADJ', 'SyspOperatorListadj'), ('DEVICECONTROL_MICROSOFT_DEFENDER', 'DevicecontrolMicrosoftDefender'), ('FINTECH_DEVICES_60', 'FintechDevices60days'), ('FINTECH_PATCH_COMPLIANCE', 'FintechPatchCompliance'), ('AGENT_SCBCK_COMBINED', 'AgentSCBCKCombined'), ('ASEC_DELTA_A_DVS_INTUNE', 'ASECDeltaADvsIntune'), ('ASECAD', 'ASECAD'), ('ADSAD_USERS', 'ADSADUsers'), ('ADS_DELTA_LICENSESVS_HR', 'ADSDeltaLicensesvsHR'), ('ADS_USER_AD_MEMBERSHIPS', 'ADSUserADMemberships'), ('ADSAD_DEVICES', 'ADSADDevices'), ('ADS_DELTA_A_DVS_INTUNE', 'ADSDeltaADvsIntune'), ('ADS_DELTA_H_RVS_AD', 'ADSDeltaHRvsAD'), ('ADS_DELTA_TICKETSVS_HR_2', 'ADSDeltaTicketsvsHR2'), ('ADS_DELTA_TICKETSVS_HR', 'ADSDeltaTicketsvsHR'), ('ASTEA_CHANGES_20252024', 'AsteaChanges20252024combined'), ('ASTEA_TICKETS_AUG_2024_AUG_2025', 'AsteaTicketsAug2024Aug2025'), ('EMPLOYEES_LICENSE_ALLOCATIONS_EXPORT_20250905164509', 'EmployeesLicenseAllocationsExport20250905164509'), ('ASTEA_CHANGES_2025', 'AsteaChanges2025'), ('ASTEA_CHANGES_2024', 'AsteaChanges2024'), ('ADSAD_EXPORT_2025', 'ADSADExport2025'), ('ADS_DELTA_INTUNEVS_HR_MASTER', 'ADSDeltaIntunevsHRMaster'), ('AD_SDELTA_HIRESVS_ALPHA_H_RLIST', 'ADSdeltaHiresvsAlphaHRlist'), ('TERMS_WD_JUN_24_APR_25', 'TermsWDJun24toApr25'), ('HIRES_WD_JUN_24_APR_25', 'HiresWDJun24toApr25'), ('ALPHALISTINC_TERMINATIONS', 'AlphalistincTerminations'), ('FINTECHDELTA_HRVS_CHANGE_CONTROLLERS_3', 'FintechdeltaHRVSChangeControllers3'), ('FINTECH_DELTA_HR_LISTVS_CHANGE_COORDINATORS', 'FintechDeltaHRListvsChangeCoordinators'), ('ADS_DELTA_SOFTWARELISTVS_INTUNE', 'ADSDeltaSoftwarelistvsIntune'), ('ADS_DELTA_INTUNEVS_SOFTWARELIST', 'ADSDeltaIntunevsSoftwarelist'), ('ADS_SOFTWARE_EXTRACT', 'ADSSoftwareExtract'), ('FINTECH_DELTA_S_YSPROUSERSVS_AD', 'FintechDeltaSYsprousersvsAD'), ('FINTECH_DELTA_TERMINATIONSVS_AD', 'FintechDeltaTerminationsvsAD'), ('AD_DEVICES', 'ADDevices'), ('AD_USERS', 'ADUsers'), ('USER_AD_MEMBERSHIP', 'UserADMembership'), ('FINTECH_DELTA_CHANGE_COORDINATORSVS_TERMINATIONS', 'FintechDeltaChangeCoordinatorsvsTerminations'), ('FINTECH_DELTA_CHANGE_COORDINATORSVS_HR_LIST_2', 'FintechDeltaChangeCoordinatorsvsHRList2'), ('FINTECH_DELTA_CHANGE_COORDINATORSVS_HR_LIST', 'FintechDeltaChangeCoordinatorsvsHRList'), ('AFTCRQ_CLOSEDWITHSUBMITDATE_REPORTADJUSTED', 'AFTCRQClosedwithsubmitdateReportadjusted'), ('FINTECH_AFTCRQ_CLOSEDWITHSUBMITDATE_CHANGE_REQUEST', 'FintechAFTCRQClosedwithsubmitdateChangeRequest'), ('FINTECH_MASTER_EMPLOYEE_FILEADJUSTED', 'FintechMasterEmployeeFileadjusted'), ('FINTECH_CRQCAB_JUN_24_JUN_25_ITGC', 'FintechCRQCABJun24Jun25vITGC'), ('FINTECH_DELTA_NEWUSERSTO_MASTER_HR_USINGSURNAME', 'FintechDeltaNewuserstoMasterHRUsingsurname'), ('FINTECH_DELTA_NEWUSERSVS_TERMINATEDUSERS', 'FintechDeltaNewusersvsTerminatedusers'), ('FINTECH_DELTA_NEWUSERSTO_MASTER_HR', 'FintechDeltaNewuserstoMasterHR'), ('FINTECH_DELTA_SYSPRO_USERSTOTERMINATIONS', 'FintechDeltaSysproUserstoterminations'), ('DELTA_MASTER_EMPLOYEEVS_TERMINATIONS', 'DeltaMasterEmployeevsTerminations'), ('FINTECH_SYSPRO_OPERATORS_LIST', 'FintechSysproOperatorsList'), ('FINTECH_SYSPRO_OPERATOR_LIST', 'FintechSysproOperatorList'), ('FINTECH_INCIDENTS', 'FintechIncidents'), ('FINTECH_CONSOLIDATED_CHANGES', 'FintechConsolidatedChanges'), ('FINTECH_MASTER_EMPLOYEE_FILE', 'FintechMasterEmployeeFile'), ('FINTECH_TERMINATIONS', 'FintechTerminations'), ('FINTECH_NEW_EMPLOYESS', 'FintechNewEmployess'), ('NU_PAY_DELTA_DEFENDERVS_INTUNE', 'NuPayDeltaDefendervsIntune'), ('NUPAY_DELTA_INTUNEVS_AV', 'NupayDeltaIntunevsAV'), ('DELTA_INTUNEVS_DEFENDER', 'DeltaIntunevsDefender'), ('DELTA_DEFENDERVS_INTUNE_2', 'DeltaDefendervsIntune2'), ('DELTA_DEFENDERVS_INTUNE', 'DeltaDefendervsIntune'), ('DELTA_AHT_INTUNEVS_DEFENDER_2', 'DeltaAHTIntunevsDefender2'), ('AHT_INTUNEVS_DEFENDER', 'AHTIntunevsDefender'), ('DELTA_INTUNEVS_AV', 'DeltaIntunevsAV'), ('DELTA_AD_2_TERMINATIONS', 'DeltaAD2vsTerminations'), ('AD_USERS_1_VS_AD_USERS_2', 'ADUsers1VsADUsers2'), ('ALTRON_HEALTH_TECH_USERS_DETAILED_2', 'AltronHealthTechUsersDetailed2'), ('DELTA_AHT_HELPDESKTICKETSTO_HR', 'DeltaAHTHelpdeskticketstoHR'), ('DELTA_NETSUITE_ACTIVE_INACTIVEVS_AD', 'DeltaNetsuiteActiveInactivevsAD'), ('DELTA_A_DVS_TERMINATIONS', 'DeltaADvsTerminations'), ('ALTRON_HEALTH_TECH_USERS_DETAILED', 'AltronHealthTechUsersDetailed'), ('NUPAY_AV_STATUS', 'NupayAVStatus'), ('ASECAV_STATUS', 'ASECAVStatus'), ('AHTAV_STATUS', 'AHTAVStatus'), ('ADSAV_STATUS', 'ADSAVStatus'), ('AHT_INTUNE', 'AHTIntune'), ('ALL_DEFENDER_INTUNE_POLICIES', 'AllDefenderIntunePolicies'), ('NUPAY_INTUNE', 'NupayIntune'), ('NUPAY_DEFENDER', 'NupayDefender'), ('NUPAY_AV', 'NupayAV'), ('ASEC_INTUNE', 'ASECIntune'), ('ASECAV', 'ASECAV'), ('ASEC_DEVICES_DEFENDER', 'ASECDevicesDefender'), ('AHT_DEFENDER', 'AHTDefender'), ('AHTAV', 'AHTAV'), ('ADS_INTUNE', 'ADSIntune'), ('ADSAV', 'ADSAV'), ('DELTA_TERMINATIONS_VS_NETSUITE_PROD', 'DeltaTerminationsVSNetsuiteProd'), ('DELTA_HRVS_NETSUITE_PROD', 'DeltaHRVSNetsuiteProd'), ('DELTA_TERMINATIONS_VSHR', 'DeltaTerminationsVSHR'), ('TERMINATIONS_VSHR', 'TerminationsVSHR'), ('TERMINATIONS_VS_ACTIVE_INACTIVE', 'TerminationsVSActiveInactive'), ('DATAFOR_IT_GENERAL_CONTROL_AUDIT_TERMINATIONS', 'DataforITGeneralControlAuditTerminations'), ('AHT_HELPDESK_TICKETS', 'AHTHelpdeskTickets'), ('NETSUITE_AHT_PRODUCTION_EMPLOYEE_SEARCH_ACTIVEAND_INACTIVE', 'NetsuiteAHTProductionEmployeeSearchActiveandInactive'), ('NETSUITE_AHT_SANDBOX_EMPLOYEE_SEARCH_ACTIVEAND_INACTIVE_RESULTS', 'NetsuiteAHTSandboxEmployeeSearchActiveandInactiveResults'), ('AHT_USER_ACTIVITIES_AUDIT_RESULTS_VSAHTHR_LIST', 'AHTUserActivitiesAuditResultsVSAHTHRList'), ('LOGIN_AUDIT_TRAIL_RESULTS_VSAHTHR_LIST', 'LoginAuditTrailResultsVSAHTHRList'), ('AHTHR_LIST_VS_ACTIVE_INACTIVE_LIST_03', 'AHTHRListVsActiveInactiveList03'), ('AHTHR_LIST_VS_ACTIVE_INACTIVE_LIST_02', 'AHTHRListVsActiveInactiveList02'), ('AHTHR_LIST_VS_ACTIVE_INACTIVE_LIST_01', 'AHTHRListVsActiveInactiveList01'), ('AHTHR_LIST_VS_ACTIVE_INACTIVE_LIST', 'AHTHRListVsActiveInactiveList'), ('INTERACTIVE_SIGN_INS_2025072120250722', 'InteractiveSignIns2025072120250722'), ('HR_DATAFOR_IT_GENERAL_CONTROL_AUDIT', 'HRDataforITGeneralControlAudit'), ('COPYOF_SL_AHOURS_MAY_2025004', 'CopyofSLAhoursMay2025004'), ('AHT_LISTOF_ACTIVEAND_INACTIVE_USERS_RESULTS_458', 'AHTListofActiveandInactiveUsersResults458'), ('AHT_LOGIN_AUDIT_TRAIL_RESULTS_676', 'AHTLoginAuditTrailResults676'), ('AHT_USER_ACTIVITIES_AUDIT_RESULTS_284', 'AHTUserActivitiesAuditResults284'), ('EMPLOYEE_LISTING_APR_25', 'EmployeeListingApr25'), ('SCHEMA_AUDIT_DATABASE_USERS', 'SchemaAuditDatabaseUsers'), ('FAVORITE', 'Favorite'), ('UNIQUE', 'Unique'), ('FINDING', 'Finding'), ('TAB', 'Tab'), ('COPY_DT', 'Copy DT'), ('FINDING_VIEW', 'Finding View'), ('IMAGE_LOADER', 'Image Loader'), ('IMAGES', 'Images'), ('FINDING_ATTACHMENT', 'Finding Attachment')], max_length=255, null=True)),
                ('description', models.TextField()),
                ('path', models.CharField(blank=True, max_length=255, null=True)),
                ('favorite_id', models.TextField(blank=True, null=True)),
                ('finding_id', models.TextField(blank=True, null=True)),
                ('img_loader_id', models.TextField(blank=True, null=True)),
                ('unique_id', models.TextField(blank=True, null=True)),
                ('tab_id', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PyFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('func', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PyFunctionPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='JoinModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_name', models.CharField(max_length=255, unique=True)),
                ('base_fields', models.TextField(blank=True, help_text='Comma separated', null=True)),
                ('delta_fields', models.TextField(blank=True, help_text='Comma separated', null=True)),
                ('base_f_key_fields', models.TextField(blank=True, help_text='Comma separated', null=True)),
                ('delta_f_key_fields', models.TextField(blank=True, help_text='Comma separated', null=True)),
                ('join_method', models.CharField(blank=True, max_length=255, null=True)),
                ('similarity_threshold', models.IntegerField(blank=True, null=True)),
                ('split_by_space', models.BooleanField(default=False)),
                ('split_character', models.CharField(blank=True, max_length=20, null=True)),
                ('match_word_position', models.IntegerField(blank=True, null=True)),
                ('pre_char', models.IntegerField(blank=True, null=True)),
                ('post_char', models.IntegerField(blank=True, null=True)),
                ('jaro_winkler', models.BooleanField(default=False)),
                ('levenshtein', models.BooleanField(default=False)),
                ('token_set_ratio', models.BooleanField(default=False)),
                ('phonetic', models.BooleanField(default=False)),
                ('fuzzy_wuzzy', models.BooleanField(default=False)),
                ('python_function', models.TextField(blank=True, null=True)),
                ('c_similarity_threshold', models.IntegerField(blank=True, null=True)),
                ('split_at', models.CharField(blank=True, max_length=20, null=True)),
                ('left_split_char', models.CharField(blank=True, max_length=20, null=True)),
                ('email_pre_char', models.IntegerField(blank=True, null=True)),
                ('email_post_char', models.IntegerField(blank=True, null=True)),
                ('base_model', models.ForeignKey(limit_choices_to={'app_label__in': ['tables', 'common']}, on_delete=django.db.models.deletion.CASCADE, related_name='base_model', to='contenttypes.contenttype')),
                ('delta_model', models.ForeignKey(blank=True, limit_choices_to={'app_label__in': ['tables', 'common']}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delta_model', to='contenttypes.contenttype')),
                ('sidebar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.sidebar')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
